### ISSUE TITLE
torch.randint issue

### ISSUE THREAD

**Issue by monet-slinky** [criteo-research/pytorch-ada#16]
Hi there,
I'm running into an error that has to do with a call to the function torch.randint() from ada/datasets/sampler.py, called from trainer.fit(model)

I thought it might be a version problem so I downgraded to version 1.2.0 of torch on Google Colab, and the error persists. I haven't changed any of the code and am trying to recreate the run_full_tests results.

Many thanks for any help!

INFO:root:Running with Namespace(data_path='/root/sync/data', dataconf='configs/datasets/office31.json', fast=False, fewshot=0, force=False, gpu=None, method='configs/default_methods.json', mlflow=None, netconf=None, nseeds=5, outdir='/root/sync/ada', tensorboard_dir=None, weighted=None)
  0% 0/5 [00:00<?, ?it/s]INFO:root:Training model with CDAN no-use_random
  0% 0/5 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "scripts/run_full_options.py", line 231, in <module>
    checkpoint_dir=checkpoint_dir,
  File "/usr/local/lib/python3.7/dist-packages/ada/utils/experimentation.py", line 360, in loop_train_test_model
    **test_params,
  File "/usr/local/lib/python3.7/dist-packages/ada/utils/experimentation.py", line 301, in train_model
    trainer.fit(model)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py", line 732, in fit
    self.run_pretrain_routine(model)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py", line 843, in run_pretrain_routine
    False)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/evaluation_loop.py", line 251, in _evaluate
    for batch_idx, batch in enumerate(dataloader):
  File "/usr/local/lib/python3.7/dist-packages/ada/datasets/sampler.py", line 65, in __iter__
    yield self._get_nexts()
  File "/usr/local/lib/python3.7/dist-packages/ada/datasets/sampler.py", line 61, in _get_nexts
    return [_get_next_dl_batch(di, dl) for di, dl in enumerate(self._iterators)]
  File "/usr/local/lib/python3.7/dist-packages/ada/datasets/sampler.py", line 61, in <listcomp>
    return [_get_next_dl_batch(di, dl) for di, dl in enumerate(self._iterators)]
  File "/usr/local/lib/python3.7/dist-packages/ada/datasets/sampler.py", line 53, in _get_next_dl_batch
    batch = next(dl)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 345, in __next__
    index = self._next_index()  # may raise StopIteration
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 318, in _next_index
    return next(self.sampler_iter)  # may raise StopIteration
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/sampler.py", line 200, in __iter__
    for idx in self.sampler:
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/sampler.py", line 106, in __iter__
    return iter(torch.randint(high=n, size=(self.num_samples,), dtype=torch.int64).tolist())
RuntimeError: invalid argument 2: max must be greater than min, but got: min = 0, max = 0 at /pytorch/aten/src/TH/generic/THTensorRandom.cpp:43

**Comment by ccrndn** [comment]
Hello monet-slinky

Actually your problem comes from the fact that the dataset you are using is empty.
`torch.randint(high=n, size=(self.num_samples,), dtype=torch.int64)` with `n == 0`

Indeed, Office31 dataset was not automatically downloaded when running the run_full_tests script with 'configs/datasets/office31.json'.
I fixed that: https://github.com/criteo-research/pytorch-ada/commit/e25d571410e8753acc8c22b281b1bb8ce0f177f1

Sorry for the inconvenience.
